ALTER TABLE `%s` ADD `id_token` VARCHAR(10) NOT NULL DEFAULT '';
ALTER TABLE `%s` CHANGE `id` `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `%s` ADD `total_kills` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT 0 AFTER `deaths`